# Generated by Django 3.2.2 on 2021-05-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('salary', models.PositiveBigIntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('last_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
