# Generated by Django 3.2.2 on 2021-05-20 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='account.user'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=10),
        ),
    ]
