# Generated by Django 3.2.2 on 2021-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210520_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='company_name',
            field=models.CharField(max_length=40),
        ),
    ]
