# Generated by Django 3.2.2 on 2021-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_applicant_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.CharField(max_length=76),
        ),
    ]
