# Generated by Django 3.2.2 on 2021-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_applicant_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
