# Generated by Django 3.2.2 on 2021-05-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_applicant_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='account.jobdetails'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.jobdetails'),
        ),
    ]
